### PR TITLE
P3 prep

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**

### CODE REVIEW

**Comment by awikkerink** [comment]
So, d2l-user-tile isn't being used anywhere. But by the semver conventions, this should be a major release. Better to do that now rather than later.

Or we could just do a minor release and hope no one notices :smirk:. We're going to do a major bump anyways...

**Comment by jstefaniuk-d2l** [comment]
I could make it a major release, shouldn't matter since no-one is using it anymore, but 🤷‍♂️

(this repo is bumped manually via the github releases tab, so a version bump would be post-pr)

**Comment by awikkerink** [comment]
Yeah, it shouldn't matter. :man_shrugging:

**Comment by jstefaniuk-d2l** [comment]
Good to merge?

**Pull request merged**
